export default {
  INITIAL_STATE: 'initial_state',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  FCM_TOKEN: 'FCM_TOKEN',
  USER_ID: 'USER_ID',
  LANGUAGE: 'APP_LANGUAGE',
  SEARCH_PRODUCTS_HISTORIES: 'SEARCH_PRODUCTS_HISTORIES',
};
